DoSomething/aurora

app/APIResponseCollection.php, app/APIResponseModel.php, app/Http/Controllers/AuroraUsersController.php, app/Http/Controllers/KeyController.php, app/Http/Controllers/UsersController.php, app/Http/routes.php, app/NorthstarKey.php, app/NorthstarUser.php, app/Providers/RouteServiceProvider.php, app/Services/Northstar.php, app/models/AuroraUser.php, config/auth.php, database/migrations/2016_01_20_194715_update_users_table.php, resources/views/errors/404.blade.php, resources/views/keys/edit.blade.php, resources/views/keys/show.blade.php
I think this pretty much wraps up the "tidying" PRs for Aurora.
This updates all controllers to use [route model binding](https://laravel.com/docs/5.1/routing#route-model-binding) to inject relevant models into the controllers (rather than having to re-write the same fetch logic in each method). It also adds a `NorthstarKey` class to wrap API key responses, and a spiffy new 404 page.
---
=> Route model binding

app/Http/Controllers/UsersController.php
Fixes an error on editing a user, since it is provided a full `NorthstarUser` object by the route model binding (added in #124) but the `edit`, `update`, and `destroy` methods still expected only a string ID.
---
=> Update edit route to expect user, rather than just ID.

app/APIResponseCollection.php, app/Exceptions/Handler.php, app/Services/Northstar.php, app/Services/RestAPIClient.php, config/services.php, public/assets/custom-neue.css, resources/views/auth/login.blade.php, resources/views/errors/500.blade.php, resources/views/keys/create.blade.php, resources/views/keys/edit.blade.php, resources/views/keys/index.blade.php, resources/views/keys/show.blade.php, resources/views/layout/errors.blade.php, resources/views/users/edit.blade.php
Adds a small helper class to clean up calls to RESTful APIs so we don’t have to have so much boilerplate. Also updates documentation!
Aurora would previously explode :bomb: if it received a `422` response from Northstar. We now explicitly catch any Guzzle client exceptions and, if it's a validation error, format and display them.
This also adds a nice 500 page (which will be used for any `HttpExceptions`, such as any uncaught exception returned from the Northstar API). This does _not_ replace fatal errors (like calling an nonexistent method), which are still sent to the Symphony "whoops" reporter.
---
For review: @angaither @weerd
=> Add RestAPIClient to clean up API classes.

app/APIResponseModel.php, app/Auth/NorthstarUserProvider.php, app/Http/helpers.php, app/NorthstarKey.php, app/NorthstarUser.php, app/Providers/AppServiceProvider.php, app/Providers/RouteServiceProvider.php, app/Services/Northstar.php, app/Services/RestAPIClient.php, resources/views/users/partials/index-table.blade.php, resources/views/users/show.blade.php
Includes updates for Northstar authentication changes in DoSomething/northstar#268.
Other notable changes:
* Removes casting from the API model class for integers, floats, strings, and booleans. I had copied this over when I extracted this stuff from Eloquent's model class, but it doesn't really make any sense to have since JSON supports all the "cartable" data types natively. Also cleans up date casting.
* Move "formatted" number helper into User model (rather than as a global helper method).
* Return `null` when an endpoint 404s. This saves us from having more try/catch blocks than we need to, and seems like a reasonable way to handle this kind of thing.
* Make `Northstar` API class a singleton and inject config values through the service container (which will help us eventually break …
=> Update for northstar auth

composer.json, composer.lock, config/app.php, config/aws.php, config/filesystems.php, config/laravel-backup.php, config/slack.php
I've added the packages to support Laravel backups.
Once on QA, you can run php artisan backup:run. The reason it can't be run locally is because the settings require s3 credentials that devs won't have on their local machines.
This is part of the disaster recovery efforts, and will make backing up via Jenkins job much easier.
=> Adding backup support

resources/views/users/show.blade.php
Adds a "Mobile Commons" line under "Connected Accounts" to display a user's Mobile Commons ID and subscription status (either `undeliverable` or `active`). This makes displaying accounts processed by [the new MobileCommons sync service](https://github.com/DoSomething/northstar-mobilecommonsd) easier.
🌵
=> Display Mobile Commons ID and status on profile.

resources/views/clients/create.blade.php, resources/views/clients/edit.blade.php, resources/views/clients/show.blade.php
This PR lets people edit the client redirect uri in Aurora. This is to help resolve some of the issues in this [issue](https://www.pivotaltracker.com/story/show/150598196).
=> Adding redirect uri to client views

app/Http/Controllers/UsersController.php, app/helpers.php, resources/views/users/index.blade.php
Since we switched to using cursor pagination, we get the wrong user count in the "intro" text. Let's make a separate query to find this out and cache it for future page views.
🔢
=> Make a separate cached query for total count.

app/Http/Middleware/CheckRole.php
You can no longer return a `Illuminate\View\View` directly from middleware in Laravel 5.2+, so this was causing a rather nasty Whoops error. Instead, use the `response()` helper to create an actual `Illuminate\Http\Response`.
=> Fix fatal error on unauthorized page.

README.md, app/Http/Controllers/Api/TotalsController.php, app/helpers.php, composer.json, composer.lock, config/auth.php, config/deploy.rb, config/services.php, resources/assets/app.js, resources/assets/app.scss, resources/assets/components/lazy-loading.scss, resources/assets/users/lazy-user-count.js, resources/views/layout/master.blade.php, resources/views/users/index.blade.php, routes/api.php, storage/keys/.gitignore
This pull request adds lazy-loading for the user count on the index page.
📄 Adds `scriptify` helper & uses it to expose user's access token to scripts. 6060360
🤖 Configures Northstar resource server using Gateway. 81f0ed6
#️⃣ Adds a API route for the user count, and a little front-end widget to show it. ce1b6e0
This is _totally_ over-engineered for the use case, but is intended a little proof-of-concept for doing the same thing in Rogue and other applications in the future. Since this endpoint is secured using a Northstar token, it could be used by any other application, in addition to Aurora web requests!
=> Lazy load the user count on the index page.

app/Http/Kernel.php
- fixes issue in user edit form where `ConvertEmptyStringsToNull` middleware sends `null` value to Northstar which we haven't properly dealt with yet there, so it wrongfully validates the empty field. We'll re-add once that's addressed.
=> temp removing ConvertEmptyStringsToNull middleware

app/Http/Controllers/UsersController.php
I noticed that page loads were still occasionally very slow, and it's because I never removed this API call from the controller (so every 15 minutes, we'd delay the request to make a full load of that count). Oy!
References #170.
=> Remove the synchronous call to get user total.

app/Http/Controllers/MergeController.php
Using the awesome new `mergeUsers` method for a cleaner call to the Northstar API when merging users.
=> using the gateway northstar API client `mergeUsers` method

app/Http/Kernel.php
Since @DFurnes updated Northstar to deal with null values in validation, we can revive this piece of middleware 🍾
=> uncommenting the ConvertEmptyStringsToNull middleware

resources/views/users/search.blade.php
Part of the update to Laravel 5.5. We don't need that view argument anymore.
https://dosomething.slack.com/archives/C02BBRN5A/p1510863519000167
=> removing faulty view argument

app/Http/Controllers/ClientController.php
This fixes a little error that was preventing me from creating new machine clients via the Aurora admin interface. The `csv_to_array` function above would output an array with a single empty string, which would fail [Northstar's `url` validation rule](https://github.com/DoSomething/northstar/blob/4737f01745acaecccdf5ccedf1db3c67fa7911d0/app/Http/Controllers/ClientController.php#L93).
=> Fix issue where machine clients would 422.

.env.example, app/Console/Commands/SetupCommand.php, config/services.php
1. Locally we now use `northstar.test` so swap out our `northstar.dev` references for that.
2. Add the `client` scope to the Northstar credentials.
=> Add client scope for Northstar

app/Http/Kernel.php, app/Http/Middleware/ForceHttps.php, composer.json, composer.lock
This pull request adds a global middleware to Aurora to force HTTPS and redirect traffic to the canonical application URL, e.g. https://dosomething-aurora-dev.herokuapp.com/ → https://admin-dev.dosomething.org.
References DoSomething/devops#388.
=> Force HTTPS traffic on production.

nginx.conf, public/.user.ini
Investigating why this always gets set to `WEB_CONCURRENCY=1`. Neither of these changes did anything, but reducing our per-process memory limit should let us spin up more processes per dyno.
References DoSomething/devops#427.
=> Some adjustments for better concurrency.

resources/views/clients/create.blade.php, resources/views/clients/edit.blade.php
This pull request includes a few UX improvements to the clients interface:
💡 Uses the `hint` parameter from DoSomething/northstar#776 to provide more help text for scopes.
ℹ️ Adds some extra inline help text for confusing fields.
⛑ Fixes issue where the "allowed grant" field would reset to "Authorization Code" when editing a machine client (and then complain that you hadn't set a Redirect URL, yadda yadda).
👀
N/A
=> Improve UX for Aurora's clients page.

package-lock.json, package.json, resources/assets/app.scss, resources/assets/components/client.scss, resources/views/clients/index.blade.php
We should all be using standard clients for our local development (and Paw/Postman requests). This helps with auditing where requests are coming from & ensures we don't accidentally leak production credentials on our local machines.
To make this clearer at a glance, this pull request adds a little highlight on `dev-` clients in Aurora:
=> Highlight clients that should be used for development.

resources/views/clients/index.blade.php, resources/views/clients/show.blade.php
I was messing around with some clients and bumped into two broken links (remnants of the `dev` branch era). Updated 'em!
=> Update links to Northstar Auth docs

app/Services/Fastly.php, resources/views/users/partials/profile.blade.php
Surfaces `voter_registration_status` on a user in Aurora.
Looks like this (don't worry, randomly generated test user!):
We want this?
🤠
=> Surface voter registration status in Aurora

app/Console/Commands/FastlyExportCommand.php, app/Console/Commands/FastlyImportCommand.php, app/Console/Kernel.php, app/Http/Controllers/RedirectsController.php, app/Resources/Redirect.php, app/Resources/RedirectCollection.php, app/Services/Fastly.php
This pull request adds `fastly:export` and `fastly:import` commands which allow us to clone dictionaries between Fastly properties (most importantly, from our current production property to the new Terraform-managed one) but also could be used to create backups of this data!
I've also fixed a few bugs with the admin flow:
- Trying to create a redirect that already exists will now overwrite the existing one rather than 500ing.
- Redirects can no longer contain query strings (because that's not supported in our new simplified VCL) and are automatically converted to lowercase (since all redirects are case-insensitive now).
=> Add commands to import/export from Fastly, and some admin updates.

app/Services/Fastly.php
Fixes an issue that @mendelB caught in #203 – paths will now always be transformed to lowercase, and separately prepended with a `/` if they don't have one. ✌️
=> Always transform path to lowercase.

resources/views/users/partials/profile.blade.php, resources/views/users/partials/subscriptions.blade.php, resources/views/users/show.blade.php
Added `email_subscription_status` and `email_subscription_topics` to user profile. I separated subscriptions out into a separate sections because I thought the list was getting a little long and hard to parse, but as you know I am _not_ a designer so happy to leave everything in one list if folks like that better!
User with no email topics:
User with email topics:
=> Add email subscription status and topics

resources/views/users/edit.blade.php
Exposes `email_subscription_status` to make testing Customer.io sync easier (refs https://github.com/DoSomething/northstar/pull/846)
=> Adds email_subscription_status

app/Http/Controllers/UsersController.php, composer.json, composer.lock, resources/views/users/partials/resets.blade.php, resources/views/users/show.blade.php, routes/web.php
Adds a new Danger Zone ™️ form for executing `POST /v/2/resets` requests, allowing admins an easy way to test Activate Account emails that'd otherwise be triggered via Chompy imports or Postman requests. Blocked by https://github.com/DoSomething/gateway/pull/122
=> Password Reset form

.env.example, config/services.php, resources/views/users/show.blade.php
Links to Customer.io, Gambit, and Rogue instead of Ashes, Mobile Commons, and Gladiator (RIP). 
The default config variables for profile URL's are set to the production values, so this will require setting config variables on QA upon merge.
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/151027088
=> Updates external profile links

resources/views/users/partials/profile.blade.php, resources/views/users/show.blade.php
Follow up from #213 -- this PR moves `source` and `source_details` out of the `-half` class and beneath the User ID heading to expose full values for lengthy `source_details`.
=> Displays source and source_details as full width

composer.json, composer.lock, config/app.php
This pull request makes [`laravel/tinker`](https://github.com/laravel/tinker) a development dependency, so it will no longer be available on production environments. While being able to easily open a REPL can be really helpful, it's also dangerous since it allows developers to execute arbitrary code on production.
[#167597101](https://www.pivotaltracker.com/story/show/167597101)
=> Disable Laravel Tinker in production.

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php
This PR adds the `voter_registration_status` field to the User's profile edit form.
https://github.com/DoSomething/aurora/pull/219/commits/d52fcbd472779266312e02ae0fa07c43460510b1 Removes a hack to strip the `sms_status` field from the Northstar payload if `null` since we've made that field `nullable`.
👀 
This won't actually completely work until we merge https://github.com/DoSomething/northstar/pull/903 to remove some hierarchy validation for arbitrary status updates and make this field `nullable` within Northstar's [Registerer validation](https://github.com/DoSomething/northstar/pull/903/files#diff-78498fe993d8f7dfd5cff7adddcdad3fR69) to allow submitting this field when it's unset or to actively unset this field.
And @katiecrane sorry to belabor this point, but I just want to confirm …
=> Add Voter Registration Status field to Profile Edit Form

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php
This PR adds support to edit the `refer-friends` feature flag value introduced in https://github.com/DoSomething/northstar/pull/915.
#220 did not let admins remove the `badges` feature flag by disabling the input, but it's pretty tricky to keep this logic for two checkboxes: If a user has the badges flag, the input is disabled. We want to give them the refer-friends feature flag, save, but then the user no longer has the badges flag because the input was disabled. I decided to go for a simpler approach by just making both flags editable. cc @ngjo
=> Edit refer-friends feature flag

app/Http/Controllers/UsersController.php
Fixes a bug in #221 to allow unsetting feature flags. I know when #220 introduced the field, it made it irremovable, but it'd be easiest to allow this for testing RAF, at least for now.
=> Editable feature flags

resources/views/users/edit.blade.php
The edit user page was breaking if one `feature_flags` value is set but not the other. Things were fine if the user had no `feature_flags` or had both `feature_flags` (here being `badges` and `refer-friends`).
@mendelB found [this tidbit](https://stackoverflow.com/questions/20009076/php-undefined-index-notice-not-raised-when-indexing-null-variable/20081922#20081922) to explain that behavior:
```
PHP won't attempt the comparison if the array is null.
In the second circumstance, a comparison does occur because the array is set. PHP does not check to see if it is empty.
```
and he also suggested using `data_get` to make sure we aren't trying to access `null` elements. I've made that update here!
=> Don't break edit user page if a feature_flag isn't set

app/Providers/RouteServiceProvider.php, app/helpers.php, composer.json, composer.lock
This is a quick follow-up to #223 that sends the `?include=` query string (which is used to conditionally display sensitive fields) along to Northstar, so that once we flip the feature-flag on this "optional fields" functionality this will all continue working!
~Blocked on https://github.com/DoSomething/gateway/pull/125 merge & release.~ Published as [v2.1.0](https://github.com/DoSomething/gateway/releases/tag/v2.1.0) and updated this app's dependencies in d27f972.
=> Send the `?include=` query string to Northstar.

app/Http/Controllers/UsersController.php, routes/web.php
This pull request includes a "quick fix" to the `users/{id}/edit` page, which was [not loading optional fields & so those fields would appear blank](https://dosomething.slack.com/archives/C02BBRN5A/p1570559704003600). Longer term, I'd like to spend a bit of time to get this working similarly to the "show" page (with 👁's), but this gets things back in working order!
References [#169023024](https://www.pivotaltracker.com/story/show/169023024)
=> Properly fetch optional fields for 'edit' form.

app/Http/Controllers/RedirectsController.php, app/Resources/Redirect.php, app/Services/Fastly.php, config/services.php, resources/views/redirects/create.blade.php, resources/views/redirects/edit.blade.php, resources/views/redirects/index.blade.php, resources/views/redirects/show.blade.php
This pull request (alongside DoSomething/infrastructure#211) removes the ability to set `301 Moved Permanently` redirects in Aurora since they're, well, permanent(!) and that's a lot of power to wield without a peer-review process.
This should be deployed after DoSomething/infrastructure#211. References [#168057201](https://www.pivotaltracker.com/story/show/168057201).
=> Remove ability to choose redirect HTTP status.

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php, resources/views/users/partials/profile.blade.php
Makes the `school_id` field introduced in https://github.com/DoSomething/northstar/pull/954 viewable/editable. This will come in quite handy for internally testing v1 of the School Finder, where users won't be able to edit their school after selecting.
=> Adds school_id field

app/Http/Controllers/UsersController.php, resources/views/home.blade.php, resources/views/search/search.blade.php, resources/views/users/partials/danger-zone.blade.php, resources/views/users/show.blade.php
This pull request hooks up the "Delete Account" interface in Aurora to Northstar's new super-charged `DELETE v2/users/{id}` endpoint. This allows admins to delete a user from Northstar, Rogue, Gambit, and Customer.io on demand:
Aurora will also now display a banner if an account has been queued for deletion:
I've also fixed up the homepage copy to direct users to `#help-product` if they need permissions.
👀
I decided to hold off on allowing admins to queue/de-queue accounts for deletion, since I think if a user requests their account to be deleted we should be very careful about "undo-ing" that change.
References [Pivotal #170953777](https://www.pivotaltracker.com/story/show/170953777).
=> Allow staff/admins to delete user accounts.

resources/views/clients/show.blade.php
This is currently a broken link to the old `/dev/` branch. Updates to `/master/`
=> Fix link to Authorization grant documentation

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php, resources/views/users/partials/subscriptions.blade.php
This pull request adds the new `sms_subscription_topics` introduced in https://github.com/DoSomething/northstar/pull/998 as a viewable/editable field on a User.
👀 
✂️ 📑 
References [Pivotal #https://www.pivotaltracker.com/n/projects/2417735/stories/171847123](https://www.pivotaltracker.com/n/projects/2417735/stories/c).
=> Adds user sms_subscription_topics

resources/views/users/show.blade.php
This pull request displays the `referrer_user_id` field on a user (added in https://github.com/DoSomething/northstar/pull/1000) if it exists.
Because it links to the referrer, I've made the link to update the user a primary one to stand out.
👀 
🔗 
References [Pivotal #170775705](https://www.pivotaltracker.com/story/show/170775705).
=> Display referrer on user view

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php
This pull request removes the `sms_subscription_topics` from the user edit form. It was interfering with setting default topics if changing from unsubscribed to subscribed, even with the check in the `UserController`. This at least unblocks merging https://github.com/DoSomething/northstar/pull/1008.
:eyes:
This was a rabbit hole :rabbit: 
References [Pivotal #2417735](https://www.pivotaltracker.com/n/projects/2417735).
=> Makes sms subscription topics read-only

app/Http/Middleware/ForceHttps.php
This pull request updates the `ForceHttps.php` middleware to remove the deprecated `League\Uri\Schemes\Http` class and use `League\Uri\Http` instead. 
After the recent [Laravel upgrade to 5.6](https://github.com/DoSomething/aurora/pull/248), our Aurora Dev & QA instances have been borked and running into a redirect loop of sorts. We suspect it's due to the upgrades leading to the full deprecation of the above class and associated method we utilized. Updating to the new class should solve the issue. 🤞 
Also does a little cleanup to ensure it applies the middleware to all non-local instances, and adds a debug logging statement for help in future troubleshooting.
👀 
=> Updating deprecated method and some cleanup.

app/Http/Middleware/ForceHttps.php
This pull request updates the debug logging message to include an initial string label which is required by the method and also helps when perusing the logs in Papertrail 🔍  It also logs more specific information since trying to log the request object would end up with more difficult to visually-read log.
=> Forcehttps middleware logging update

app/Http/Kernel.php, app/Http/Middleware/ForceHttps.php
This pull request hopefully completes my whirlwind journey to resolve a bug I introduced in #247 when I changed the ordering of the middleware.
In the prior PR, I naively thought it would be best to run the `ForceHttps` earlier on in the middleware process, but as it turns out part of the internal logic for that middleware depends on the `TrustProxies` having been set. Thus, we were having a crazy redirection loop happening. It took a while to figure out what exactly was going on, but I strongly suspect this simple change was the culprit!
I added a comment in the `ForceHttps` middleware to know that it needs to happen after `TrustProxies`.
🙏  this fixes things!
👀 
=> Fixing bug with middleware order.

resources/views/clients/index.blade.php
This pull request fixes a bug due to forgetting to update the `starts_with()` helper function to switch it to using the `Str` class.
👀 
Forgot to include this in the 6.x upgrade: https://github.com/DoSomething/aurora/pull/254
=> Missed switching to Str class.

app/Http/Controllers/UsersController.php, resources/views/users/edit.blade.php, resources/views/users/partials/field.blade.php, resources/views/users/partials/interests.blade.php, resources/views/users/partials/profile.blade.php, resources/views/users/partials/subscriptions.blade.php, resources/views/users/show.blade.php
This pull request adds the new `club_id` user attribute (https://github.com/DoSomething/northstar/pull/1046) and the `clubs` email subscription topic (https://github.com/DoSomething/northstar/pull/1048) to the user show & edit views.
While we were here, it also addresses [Pivotal #174585290](https://www.pivotaltracker.com/n/projects/2328687/stories/174585290) where `&mdash;` _within strings_ were being rendered onto the page. We update this by simply replacing the encoding with the literal `—` character.
👀 
References [Pivotal #174106253](https://www.pivotaltracker.com/story/show/174106253).
References [Pivotal #174585290](https://www.pivotaltracker.com/n/projects/2328687/stories/174585290).
=> Add Clubs Fields

.env.example, config/services.php, resources/views/users/partials/profile.blade.php, resources/views/users/show.blade.php
This pull request links to a user's club in Rogue if available.
https://github.com/DoSomething/aurora/commit/3d1c17a023dc5f6989b77bb355c8c6038867d7c4 replaces the `ROGUE_PROFILE_URL` with a `ROGUE_URL`, and instead inlines the profile path directly. We seem to only use this in one spot, so the benefit of the general `ROGUE_URL` seems like a good tradeoff. (I opted not to maintain the additional `ROGUE_PROFILE_URL` since that seemed like overkill).
I'd love feedback on if this approach re env variables makes sense.
And if the actual link implementation makes sense, this could be neat to extract into a partial and apply for the users school ID field as well.
This should make the admin experience a lot more convenient when dealing with user clubs.
References [Pivotal …
=> Link To User's Club in Rogue
