DoSomething/aurora

app/Aurora/Services/Northstar.php
app/controllers/SessionsController.php
app/controllers/UsersController.php

Update to match new data array

---

app/controllers/UsersController.php

Update edit user function.

---

app/database/seeds/UserTableSeeder.php

Fixes #18 where id is different from northstar.

fixing bug issue #18

---

app/views/layout/master.blade.php
app/views/users/index.blade.php
app/views/users/partials/search.blade.php
app/views/users/partials/waypoints.blade.php
public/assets/custom-neue.css

Fixes #31 
@angaither 
@DFurnes

User index

---

app/views/layout/master.blade.php
app/views/users/edit.blade.php
public/assets/custom-neue.css

Fixes #32 
@angaither 
@DFurnes

User edit page

---

app/Aurora/helpers.php
app/views/hello.blade.php
app/views/layout/master.blade.php
app/views/layout/nav.blade.php
app/views/users/partials/details.blade.php
app/views/users/partials/search.blade.php
app/views/users/partials/trigger-modal.blade.php
app/views/users/show.blade.php
public/assets/custom-neue.css

Fixes issue #33 
@angaither 
@DFurnes

User show page

---

app/views/hello.blade.php

removed bootsrap class from root page

---

package.json

Fixes #43 for not being able to pull down node_modules
@angaither 
@DFurnes

added main package.json file

---

app/views/users/partials/search.blade.php

references issue #47 
@angaither 
@DFurnes

add magnifying glass and secondary class to buttons

---

app/views/users/partials/details.blade.php

Fixes #48 drupal data without var_dump
@angaither
@DFurnes

change user:campaigns styling without variable types

---

app/controllers/UsersController.php
app/views/users/partials/details.blade.php
app/views/users/partials/make-admin.blade.php
app/views/users/show.blade.php
public/assets/custom-neue.css

References #48 bullet 4
@angaither 
@DFurnes

added admin button in red and fix user search button

---

app/Aurora/Services/Drupal.php
app/controllers/UsersController.php
app/views/users/partials/details.blade.php
app/views/users/partials/reportbacks.blade.php
app/views/users/show.blade.php

References #34
@DFurnes 
@angaither 
We had a question about whether or not we should display all reportback-items for each campaign or just the first one? The staging.beta site only displays the first reportback-item so we went with that.
Also, should we also display the caption and "why participated" in the reportbacks or just the 3 things you referenced in the issue? We only displayed the 3 mentioned in the issue.

Reportback item

---

wercker.yml

Adding NPM install and gulp build to deploy tasks.
Resolves #60 
@angaither

Adding npm install and gulp build

---

app/views/users/index.blade.php

References #68 
@angaither 
@DFurnes

number_format on total users

---

app/controllers/UsersController.php
app/views/users/edit.blade.php
app/views/users/partials/details.blade.php

Fixes #62 
@angaither 
@DFurnes

Fix user attributes

---

app/views/layout/master.blade.php

changed jquery to https from cdnjs

---

app/views/users/admin-index.blade.php
app/views/users/partials/index-table.blade.php

References #72
@angaither @DFurnes 
qa page errors out when there is no admin user found.

fixing page error for no admin found

---

app/views/users/index.blade.php
app/views/users/partials/campaigns.blade.php
app/views/users/partials/index-table.blade.php
app/views/users/partials/reportbacks.blade.php

Fixes #78 
@DFurnes @angaither Safety comes first

santize for extra layer of protection

---

app/views/sessions/login.blade.php
app/views/sessions/partials/login-form.blade.php
app/views/sessions/signin-modal.blade.php

@DFurnes @angaither 
So, using a partial form instead of having 2 forms for login.

Using partial for login form

---

app/filters.php
app/views/sessions/unauthorized.blade.php

References #82 
@DFurnes 
@angaither

Unauthorized page

---

app/controllers/UsersController.php

Fixes #81 @angaither @DFurnes @jonuy 
Talking about old northstar data that doesnt gives back drupal_id with @jonuy.
Hopefully this will solve the problem for now.

conditional checking if campaigns doesnt have drupal_id

---

app/Aurora/helpers.php
app/views/hello.blade.php
app/views/users/partials/index-table.blade.php

@DFurnes @angaither 
I think I got it right this time...

changed helper functions from camelCase to snake_case

---

app/controllers/UsersController.php
app/routes.php
app/views/users/partials/details.blade.php
app/views/users/partials/remove-admin.blade.php

@DFurnes  @angaither 
Very minor change, the routes were conflicting so I had to change the route. I thought I had done this in the Admin-fix pull request but I must have undone it before I pushed.

fixed admin remove route

---

app/views/users/index.blade.php
app/views/users/partials/waypoints.blade.php
public/assets/custom-neue.css

@DFurnes @angaither 
Pagination with numbers. Looks much better than before and move it to the bottom of the table.

Pagination with numbers

---

app/Http/Controllers/UsersController.php
app/Http/Middleware/CheckRole.php
app/models/User.php

Allow a route/controller to be limited to any of an array of roles (e.g. users can be viewed by admins _or_ staff _or_ interns). :hand: 
---
For review: @angaither or @weerd

Grant permission to multiple roles.

---

app/Http/Controllers/UsersController.php
resources/views/search/search.blade.php
resources/views/users/search.blade.php

This fixes the broken search functionality in Aurora. Awesome! Staff can now search for members by Northstar ID, Drupal ID, email, or phone (including portions of any of those fields).
Note, this relies on [some changes in Northstar](https://github.com/DoSomething/northstar/pull/257).
Closes #26.
---

Working search! Woohoo!

---

app/APIResponseCollection.php
app/Http/Controllers/UsersController.php
app/Services/Northstar.php
resources/views/users/search.blade.php

Fixes some teensy bugs in pagination – namely, that search results _couldn't_.
---

Search bugfixes

---

app/Http/Controllers/UsersController.php
resources/views/users/search.blade.php

Fixes an issue paginating the search results page (due to API changes made in Northstar PHP package).
---

Fix pagination on search page.

---

composer.json
composer.lock

Fixes #132. Searching for a user account no longer gives you a fatal error. :boom: 
---
For review: @angaither @weerd

Update PHP library & other dependencies.

---

composer.json
composer.lock

Updates to use v1.0.0-rc5 of the Northstar client. See DoSomething/northstar-php#20.
---
For review: @weerd

Update to use v1.0.0-rc5 of Northstar client.

---

app/Http/Controllers/ClientController.php
resources/views/clients/index.blade.php
resources/views/clients/show.blade.php

Takes advantage of the new public key route and refresh token count added in DoSomething/northstar#389.
---
For review: @weerd @angaither

Admin touchups

---

composer.json
composer.lock

Updates Guzzle to version 6.2.1. References DoSomething/devops#148.
---
For review: @angaither @weerd

Update Guzzle version.

---

resources/assets/app.scss

I broke this out into a partial but forgot to import it to the main stylesheet in #140. Oy.
---
For review: @sbsmith86

Add the danger zone partial.

---

README.md

Add responsible disclosure policy.

---

app/Http/Controllers/ClientController.php
composer.json
composer.lock
package.json
resources/assets/app.js
resources/assets/utilities/confirm.js
resources/assets/utilities/dom-ready.js
resources/assets/utilities/form-loader.js
resources/assets/utilities/method-link.js
resources/views/clients/create.blade.php
resources/views/clients/edit.blade.php
resources/views/clients/index.blade.php
resources/views/layout/master.blade.php

More fixes and small improvements, including changes related to DoSomething/northstar-php#23.
🔜 Redirects to the correct path after creating a new OAuth client (rather than 404ing).
📟 Adds pagination for the clients index (thanks to using the new `v2/clients` endpoint in Northstar-PHP now).
📄 Adds "title" and "description" fields when creating a new client.
📘 Show the clients' titles on the index page (rather than the potentially less clear Client ID).
☕ Adds the JS helpers from Voting App so that we can have nice clickable "form buttons" and "Did you mean to do this thing?" confirmation alerts.
---

More fixes

---

.env.example
config/services.php
resources/views/users/show.blade.php

Adds a little "convenience" link to jump to a user's Gladiator profile (if it exists).
---

Add Gladiator profile link.

---

app/Http/Controllers/UsersController.php
composer.json
composer.lock
config/services.php

This PR updates Aurora to use the latest Northstar-PHP, and also makes a few little clean-up commits.
---
For review: @weerd

Northstar-PHP 1.0.0 RC9

---

app/models/AuroraUser.php
composer.json
composer.lock

Update to latest Northstar-PHP release candidate.

---

app/Http/Controllers/Auth/AuthController.php
app/Http/Controllers/ClientController.php
app/Http/Controllers/SuperusersController.php
app/Http/Controllers/UsersController.php
app/Providers/RouteServiceProvider.php
app/models/AuroraUser.php
composer.json
composer.lock
config/app.php

Updates to point to the new name for the package formerly known as Northstar-PHP :wheel_of_dharma:
---
For review: @weerd

Update to use newly renamed Gateway package.

---

config/laravel-backup.php
wercker.yml

This PR is to convert deploys from the Classic Wercker deploys to their new Docker based system. I've updated the build box to use a DS specific Laravel build box. https://hub.docker.com/r/dosomething/ds-docker-php/
cc: @pnasrat

Wercker docker

---

app/Services/MobileCommons.php
composer.json
composer.lock
database/migrations/2017_05_16_104632_increase_token_field_length.php

This pull request updates Aurora to use the latest stable Gateway release, updates all our other dependencies, and adds support for longer Northstar tokens via the [packaged Gateway migration](https://github.com/DoSomething/gateway/releases/tag/v1.3.0).

Accept longer Northstar tokens.

---

app/Http/Controllers/ClientController.php
app/Http/Controllers/SuperusersController.php
app/Providers/RouteServiceProvider.php
resources/views/clients/index.blade.php
resources/views/superusers/index.blade.php
routes/web.php

Accidentally borked my rebase on #162. 🤦‍♂️ Also including some more fixes for Laravel upgrade:
👥 Fixes query string logic on the superusers page.
🍯 Restores accidentally deleted route-model binding.
🏠 Sets the homepage as a named `login` route for built-in Authenticate middleware.

Re-apply #162 and fix some Laravel upgrade issues.

---

app/Http/Controllers/ClientController.php

Ensure all scopes can be removed from a client.

---

package-lock.json
package.json
resources/views/layout/master.blade.php
webpack.config.js

This pull request updates Aurora to use the latest versions of our [Webpack](https://github.com/DoSomething/webpack-config) and [Babel](https://github.com/DoSomething/babel-config) configs. In particular, this gives us hashed asset URLs (so we don't have caching issues on deploys) & support for ES2016+ language features.

Update Webpack & Babel.

---

README.md
app/Console/Commands/SetupCommand.php
app/Console/Kernel.php
composer.json
composer.lock

I made a [fun thing](https://github.com/DFurnes/environmentalist) over the weekend, let's use it here!

Add setup command powered by Environmentalist.

---

composer.json
composer.lock
package-lock.json
resources/views/users/show.blade.php

- Pulls in new Gateway fixes and displays errors on user edit form

Fix validation error issues.

---

app/Http/Controllers/MergeController.php
resources/views/users/merge/create.blade.php
resources/views/users/partials/profile.blade.php
resources/views/users/show.blade.php
routes/web.php

- Adds new user profile partial to display user profile fields 🏑 
- Adds form to user show page to input dup user id if for merging 🦆 
- Controller to handle previewing and confirming user merge 🎁 
- Actual merging post-confirmation is not yet implemented, pending some work on errors in `Northstar`🎢 
- This is pretty much all Dave but I shall take the credit shamelessly :trollface: 
https://www.pivotaltracker.com/story/show/148973339

User merge

---

resources/views/users/show.blade.php

Just some quick visual tweaks from peeking at the merge form on Thor:

Tweaks to the merge form.

---

app/Http/Controllers/MergeController.php
resources/views/users/merge/create.blade.php

Implementing the endpoint for actually merging User profiles 👥

User merge additions

---

CODEOWNERS
wercker.yml

This pull request adds a `CODEOWNERS` file so we [automatically request reviews](https://github.com/blog/2392-introducing-code-owners) from Team Rocket.
I also made one small tweak to our Wercker file so we're not `sudo` installing modules. 😨
🚀
N/A

Automatically request reviews from Rocket.

---

CODEOWNERS
Procfile
app.json
app/Http/Middleware/TrustProxies.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
config/database.php
config/trustedproxy.php
nginx.conf
package.json

This pull request adds the necessary configuration to deploy Aurora to Heroku, so we can save a few bucks and simplify things! References DoSomething/devops#388.

Configure Aurora for Heroku.

---

app/Console/Commands/SetupCommand.php

Just updating the setup command to have the correct Northstar URLs.
References DoSomething/devops#383.

Update setup command.

---

composer.lock
package-lock.json
package.json
resources/assets/app.js

This pull request adds the [environment-badge](https://github.com/DoSomething/environment-badge) package to Aurora, which applies a "local", "dev, or "QA" badge to each respective environment to make it easier to tell them apart:
<br/>
👀! I've also updated other dependencies in 3c57b24.
References DoSomething/infrastructure#47.

Use environment-badge package.

---

app/Http/Controllers/UsersController.php
resources/views/users/edit.blade.php

Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/164769906.

Adds email_subscription_topics to user edit form

---

resources/views/users/partials/danger-zone.blade.php
resources/views/users/partials/profile.blade.php
resources/views/users/show.blade.php

We use this field quite a bit in Customer.io so it'd be nice to expose in Aurora. This PR also moves the danger zone into its own partial, because it has the best name.

Display user source detail

---

resources/views/users/partials/profile.blade.php

Front-end for https://github.com/DoSomething/northstar/pull/958.

Displays school_id_preview

---

app/Http/Controllers/UsersController.php
package-lock.json
package.json
postcss.config.js
resources/views/users/edit.blade.php

This PR adds the new `refer-friends-scholarship` field to the User admin view and form as per the new attribute in https://github.com/DoSomething/northstar/pull/963
[Pivtoal #169376190](https://www.pivotaltracker.com/story/show/169376190)

Add refer-friends-scholarship feature flag to User's view/form

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
CODEOWNERS

This pull request updates this app's `CODEOWNERS` (for automatic review assignment) and adds a `PULL_REQUEST_TEMPLATE` to this repository.
👀
🤖
References [Pivotal #169782630](https://www.pivotaltracker.com/story/show/169782630).

Add CODEOWNERS and PULL_REQUEST_TEMPLATE.

---

composer.json
composer.lock
package-lock.json
package.json
resources/views/users/index.blade.php

This pull request removes the user counter from the index page, since it's currently [timing out](https://www.pivotaltracker.com/story/show/170078318) and causing unnecessary errors. I've also updated Composer & NPM dependencies.
👀
💹
References [Pivotal #170078318](https://www.pivotaltracker.com/story/show/170078318).

Remove user count from Aurora index.

---

resources/views/users/partials/interests.blade.php
resources/views/users/show.blade.php

This pull request surfaces causes on a user profile under a new `Interests` section!
👀  - I separated it from the other subscriptions since that is how it's categorized on their profiles as well. Does that makes sense?
Finally surfacing these after adding them to the registration process in the fall! 
References [Pivotal # 169194049](https://www.pivotaltracker.com/story/show/169194049).

Add causes to user profiles

---

app/Http/Controllers/UsersController.php
resources/views/users/edit.blade.php

This pull request adds the causes to the `update profile` form for users in Aurora.
👀 
Follow up to surfacing causes on the users profile. 
References [Pivotal # 169194049](https://www.pivotaltracker.com/story/show/169194049).

Adds causes to the edit profile form

---

resources/views/users/edit.blade.php

This pull request adds UI updates for https://github.com/DoSomething/northstar/pull/1007. 
👀 
No
References [Pivotal #171848124](https://www.pivotaltracker.com/story/show/171848124).

Adds "general" option to SMS subscription topics

---

.env.example
.gitignore
app/Http/Controllers/SuperusersController.php
app/Http/Kernel.php
app/Http/Middleware/ForceHttps.php
app/Providers/AppServiceProvider.php
app/Providers/AuthServiceProvider.php
app/Resources/Redirect.php
composer.json
composer.lock
config/app.php
config/broadcasting.php
config/cache.php
config/database.php
config/mail.php
config/queue.php
config/services.php
config/session.php
database/.gitignore
database/factories/UserFactory.php
phpunit.xml
resources/lang/en/passwords.php
resources/lang/en/validation.php
resources/views/redirects/index.blade.php
resources/views/users/partials/profile.blade.php
resources/views/users/partials/sensitive-field.blade.php
routes/web.php

This pull request upgrades Aurora from Laravel 5.7 to 5.8! 🆙 
👀 
Since the app lacks PHP Unit tests, I'm taking this one upgrade at a time!

Upgrading Laravel to 5.8

---

app/Console/Commands/SetupCommand.php
app/Http/Kernel.php
resources/views/clients/edit.blade.php
resources/views/users/partials/field.blade.php
resources/views/users/partials/sensitive-field.blade.php

This pull request does some general cleanup and fixes a bug with some string helpers I had forgotten to update (and causing an error on QA & Dev). It also updates the `auroroa:setup` command similar to what was done for [Rogue](https://github.com/DoSomething/rogue/pull/1101) due to the same error experienced when running it.
👀 
🌵 

General cleanup

---

app/Console/Commands/SetupCommand.php

This pull request updates the setup command to use the updated `runArtisanCommand()` from the Environmentalist package. @DFurnes [helped clarify](https://gist.github.com/DFurnes/5dad7f34a4d89fcdc1a7b83fcad39631#gistcomment-3423465) what was going on and what had changed.
Confirmed everything is working and outputting nicely as before:
👀 

Updating setup command.

---

.circleci/config.yml
composer.json
composer.lock

This pull request updates Aurora to use PHP 7.4. This allows us to use new language features, like arrow functions, and prepares us for the end of PHP 7.3's [active support window](https://www.php.net/supported-versions.php).
I've split this work into separate commits for each change.
This is the last application we needed to update to PHP 7.4!
References [Pivotal #173629223](https://www.pivotaltracker.com/story/show/173629223).

Update Aurora to PHP 7.4.

---

composer.json
composer.lock

This pull request adds the [gettext](https://www.php.net/manual/en/intro.gettext.php) extension to this application, which should clear up [some issues](https://dosomething.slack.com/archives/CUQMU4Q6B/p1611074042002300) we're running into with parsing ISO codes into human-readable text:
```
Call to undefined function bindtextdomain() (View: /app/resources/views/users/partials/profile.blade.php) (View: /app/resources/views/users/partials/profile.blade.php)
https://admin.dosomething.org/users/58b5e2a7a0bfad7e1c63ebb4
```
👀
This extension is newly required for the [php-isocodes](https://github.com/sokil/php-isocodes) library.
References [Pivotal #176559914](https://www.pivotaltracker.com/story/show/176559914).

Update dependencies & include ext-gettext.
